version: '1'
services:
  postgres:
      container_name: recipes-db
      restart: always
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - DEBUG=false
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=wspwsp321
        - POSTGRES_DB=recipes-db
      networks:
          - recipes-network
  recipes-server:
        container_name: recipes-backend
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "8080:8080"
        environment:
          SPRING_APPLICATION_NAME: recipes-manager
          SPRING_PROFILES_ACTIVE: docker-local
        networks:
          - recipes-network
networks:
  recipes-network:
    driver: bridge
