server:
  port: 8081
spring:
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate.ddl-auto: update
    database-platform: org.hibernate.dialect.HSQLDialect
  datasource:
    url: jdbc:hsqldb:mem:recipes-db
    username: sa
    password:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
